### PR TITLE
PEP 8

### PR DESCRIPTION
**Pull request by hvelarde**

### CODE REVIEW

**Comment by jensens** [comment]
is this still WIP? Or shall we merge?

**Comment by hvelarde** [comment]
WIP, but I'm busy at the moment

**Comment by hvelarde** [comment]
@jensens I saw you're already working on a Plone 5 branch and merging this will probably cause a bunch of headaches; I tried to separate every thing so we can probably cherry pcik some commits while leaving others unmerged.

**Comment by jensens** [comment]
I just merged an already submitted PR with Plone 5 compat work

**Comment by hvelarde** [comment]
ok, then I'll restart this.

**Comment by hvelarde** [comment]
but you merge it on a different branch; how are we going to maintain this? I think is better to create a 1.x branch from master and then merge [plone5](https://github.com/plone/plone.app.ldap/tree/plone5) into master as 2.x.

then I can merge this into 1.x and start working on 2.x on the same.

**Comment by jensens** [comment]
having two branches for 4.3 and 5.0 sounds sane - but i'am not deep into this project, i just try to manage PR's

**Comment by jensens** [comment]
with plone 5 release and changes done in this package, this PR looks somewhat outdated. I close it, if different opinion please just reopen.

**Pull request closed without merging**
