### PR TITLE
make explicit that this does not work with Plone 5

### PR DESCRIPTION
**Pull request by tkimnguyen**

### CODE REVIEW

**Comment by gforcada** [comment]
That's interesting... mr.roboto thinks that plone.app.ldap is being used on 5.0 and 5.1 but your changes here say quite the opposite. Should we remove p.a.ldap from 5.0 and 5.1 for good?

**Comment by tkimnguyen** [comment]
Huh, where is plone.app.ldap used in Plone 5.0 and 5.1? I freely admit my ignorance - I can't tell what to look at in the detail links above :) 

I just looked at an install I have of Plone... I usually use the unified installer. And sure enough it seems to include p.a.ldap 1.4.0 ...

https://github.com/plone/Installers-UnifiedInstaller/blob/ff1cf05f27441b3608379ca35906899b61939464/base_skeleton/versions.cfg#L319

Is it really used for anything? Maybe @smcmahon knows

**Comment by mauritsvanrees** [comment]
`plone.app.ldap` is just there as a helper for people who do use it, just like we have pins for `Products.LinguaPlone` in several coredev branches, even though core does not use it.

If it does not work on 5.0 and 5.1, it would indeed be better to remove it there.

**Comment by tkimnguyen** [comment]
I think it would be better to remove it, because I haven't heard of a single successful use of it with Plone 5.x – only problems – and the consistent message I've seen is that pas.plugins.ldap is the way to go. Maybe we should add the pas.plugins.ldap pin instead? (or as another PR?)

**Comment by jaroel** [comment]
I can login as a user just fine, if I add the ldap server via the ZMI.
This just needs some lovin'.

**Comment by tkimnguyen** [comment]
I think this is the problem, @jaroel ... until it gets that lovin feelin, people who install it will get tripped up

**Pull request closed without merging**
